### ISSUE TITLE
Windows resize while moving them around

### ISSUE THREAD

**Issue by hirad1986** [nclarius/tile-gaps#15]
When the script is enabled, whenever I want move the window around (either by the titlebar or holding the meta key and dragging it from any place), the window resizes. 
Using Arch Linux, Plasma 5.25.1 and tried both git and version 7.1
https://user-images.githubusercontent.com/95542349/175828791-5f87c80b-ef76-4b2b-8dfb-93d487fdb218.mp4

**Comment by twocore** [comment]
I can confirm this on Manjaro KDE with Plasma 5.24.5 / KDE Framework 5.95 & QT 5.15.5. If the script is activated, the windows changes their size while moving them. If i changed ``Gaps on`` from ``all`` do ``none``, the shrinking no longer occurs.

Output from journalctl (Dolphin moved around):

```
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1796 953 2749 y 1781 628 2409
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1796 953 2749 y 1781 628 2409
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1782 628 2410
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1782 628 2410
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1783 628 2411
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1783 628 2411
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1784 628 2412
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1797 953 2750 y 1784 628 2412
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1798 953 2751 y 1786 628 2414
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1798 953 2751 y 1786 628 2414
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1798 953 2751 y 1787 628 2415
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1798 953 2751 y 1787 628 2415
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1788 628 2416
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1788 628 2416
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1789 628 2417
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1789 628 2417
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1790 628 2418
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1790 628 2418
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1791 628 2419
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1799 953 2752 y 1791 628 2419
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1791 628 2419
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1791 628 2419
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1792 628 2420
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1792 628 2420
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: client geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1793 628 2421
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps:
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: frame geometry changed Downloads — Dolphin
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: gaps for Downloads — Dolphin x 1800 953 2753 y 1793 628 2421
Jul 04 14:02:16 flounder kwin_x11[852]: js: tilegaps: area x 1 3440 3441 y 1472 1408 2880
```

**Comment by robinsrk** [comment]
I am also facing the same issue. Any trick to fix the issue? or have to wait for update?

**Comment by cazacugmihai** [comment]
I also have this issue.

Distributor ID:	Neon
Description: KDE neon User - 5.25
Release: 20.04
Windows Gaps 7.1

**Comment by LiYulin-s** [comment]
I am facing the same problem.

Using Archlinux with Plasma 5.25.4,Windows Gaps 7.1.

**Comment by enly1** [comment]
And another on KDE Neon: OS: KDE neon User - 5.25 x86_64

**Comment by pdimens** [comment]
+1 to experiencing this on Manjaro + KDE

**Comment by DominicusPurple** [comment]
same here on debian sid

**Comment by nclarius** [comment]
Thanks for the report, and sorry for the long inactivity. It should be fixed with the update I just released. If not, please reopen this thread.

**Comment by robinsrk** [comment]
Still facing the issue. and another thing is window isn't maximized. i mean i have hidden the titlebar on maximized window. but it shows when i use this module and try to maximize any window.

**Comment by MathisP75** [comment]
I am still facing this issue, but it occurs when moving the window near the edges of the screen. The window snaps to the gap and gets resized.

**Comment by MathisP75** [comment]
I think I fixed it by removing the trigger "client.frameGeometryChanged". I don't know if it's gonna cause other problems, I will see.

**Comment by gazsp** [comment]
Same issue here. Debian 12 (bookworm), Plasma 5.27.2.
